### ISSUE TITLE
Can't make it work in drupal 7

### ISSUE THREAD

**Issue by sunnycs121** [drupal-code-builder/drupal-code-builder#226]
Placed drupal-code-builder library in sites/all/libraries, added dependencies through composer but when page /admin/config/development/module_builder/update is visited, seeing following error:

_Error: Class 'DrupalCodeBuilder\Factory' not found in module_builder_init_library() (line 43 of /code/sites/all/modules/module_builder/module_builder.module)._

Drupal version: 7.78
Module Builder version: 7.x-2.1

**Comment by joachim-n** [comment]
Which version of Drupal Coder Builder are you using?

**Comment by sunnycs121** [comment]
4.1

**Comment by joachim-n** [comment]
You should probably be on 3.latest.

But it sounds like there's a problem with the library loading in the first place.

**Comment by joachim-n** [comment]
Works fine for me if I used Drupal Code Builder 3.latest - https://github.com/drupal-code-builder/drupal-code-builder/releases/tag/3.3.19

I'll update the README for MB.

**Comment by joachim-n** [comment]
I've got this working locally with DCB 3.latest, so the problem was that you were using DCB 4. 

Fixed the incorrect README in MB to say you should use version 3.

**Comment by sunnycs121** [comment]
After putting in 3.3.19 library version still getting following error on page _admin/config/development/module_builder/update_:

Error: Class 'Drupal' not found in DrupalCodeBuilder\Environment\VersionHelper8->prepareDirectory() (line 60 of /code/sites/all/libraries/drupal-code-builder/Environment/VersionHelper8.php).

Drupal module version: 7.x-2.2

I did run composer update in sites/all/libraries/drupal-code-builder
![image](https://user-images.githubusercontent.com/2493730/113057905-9d3da580-917b-11eb-991a-4c7508289345.png)

**Comment by joachim-n** [comment]
Ok, that's fixed. Try 3.3.20.

**Comment by sunnycs121** [comment]
That worked. Thanks much!!
